# Generated by Django 4.2.3 on 2023-07-04 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabania',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('Apart', 'Apart'), ('Cabaña', 'Cabaña'), ('Departamento', 'Departamento'), ('Habitacion', 'Habitacion')], max_length=15)),
                ('capacidad', models.CharField(max_length=2)),
                ('precio', models.FloatField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_nombre', models.CharField(max_length=100)),
                ('dni', models.IntegerField(default=0)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(default='user@gmail.com', max_length=50)),
                ('pais', models.CharField(default='Argentina', max_length=30)),
                ('provincia', models.CharField(default='Cordoba', max_length=30)),
                ('localidad', models.CharField(default='Cordoba', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Complejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('cabania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cabania')),
            ],
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.CharField(default='user@gmail.com', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(default='nada', max_length=150)),
                ('precio', models.FloatField(default=0, max_length=20)),
                ('incluido', models.CharField(choices=[('si', 'si'), ('no', 'no')], default='no', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaEntrada', models.DateField()),
                ('diaSalida', models.DateField()),
                ('seña', models.FloatField(default=0, max_length=12)),
                ('precio', models.FloatField(default=0, max_length=12)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.cliente')),
                ('complejo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.complejo')),
            ],
        ),
        migrations.AddField(
            model_name='complejo',
            name='encargado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.encargado'),
        ),
        migrations.AddField(
            model_name='cabania',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.servicio'),
        ),
    ]
