# Generated by Django 4.2.3 on 2023-07-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabania',
            name='servicio',
        ),
        migrations.AddField(
            model_name='cabania',
            name='servicio',
            field=models.ManyToManyField(to='reservas.servicio'),
        ),
    ]
