# Generated by Django 4.2.3 on 2023-07-04 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_cabania_servicio_cabania_servicio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cabania',
            old_name='servicio',
            new_name='servicios',
        ),
    ]
