# Generated by Django 4.2.3 on 2023-07-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0003_rename_servicio_cabania_servicios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='incluido',
        ),
        migrations.AddField(
            model_name='servicio',
            name='nombre',
            field=models.CharField(default='nada', max_length=20),
        ),
    ]
