# Generated by Django 4.2.3 on 2023-07-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0005_remove_cabania_servicios_reserva_cabania_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complejo',
            name='cabania',
        ),
        migrations.AddField(
            model_name='complejo',
            name='cabanias',
            field=models.ManyToManyField(to='reservas.cabania'),
        ),
    ]
