# Generated by Django 4.2.3 on 2023-07-04 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0006_remove_complejo_cabania_complejo_cabanias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicio',
            old_name='nombre',
            new_name='codigo',
        ),
    ]
