# Generated by Django 4.2.3 on 2023-07-04 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0008_remove_complejo_cabanias_cabania_complejo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cabania',
            name='complejo',
        ),
        migrations.AddField(
            model_name='cabania',
            name='complejo',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reservas.complejo'),
        ),
    ]
