# Generated by Django 4.2.3 on 2023-07-04 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0009_remove_cabania_complejo_cabania_complejo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabania',
            name='complejo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.complejo'),
        ),
    ]
