# Generated by Django 4.2.1 on 2023-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0012_remove_reserva_servicios_reserva_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='dni',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
