# Generated by Django 4.2.1 on 2023-08-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0013_encargado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='dni',
            field=models.IntegerField(default=0),
        ),
    ]
