# Generated by Django 4.2.1 on 2023-08-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0015_alter_encargado_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='encargado',
            name='dni',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='codigo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='descripcion',
            field=models.CharField(default='ninguna', max_length=150),
        ),
    ]
