# Generated by Django 4.2.3 on 2023-09-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0016_alter_cliente_dni_alter_encargado_dni_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='servicios',
        ),
        migrations.AddField(
            model_name='reserva',
            name='servicios',
            field=models.ManyToManyField(to='reservas.servicio'),
        ),
    ]
