# Generated by Django 4.2.3 on 2023-11-02 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0018_rename_codigo_servicio_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='reservaservicio',
            name='cantidad',
        ),
    ]
