# Generated by Django 4.2.3 on 2024-02-27 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0019_remove_reserva_precio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='precio_original_cabania',
            field=models.FloatField(default=0),
        ),
    ]
