# Generated by Django 4.2.3 on 2024-03-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0020_reserva_precio_original_cabania'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservaservicio',
            name='precio_original_servicio',
            field=models.FloatField(default=0),
        ),
    ]
